### ISSUE TITLE
Active styles incorrects

### ISSUE THREAD

**Issue by Garito** [ghinda/css-toggle-switch#42]
Hi!
I'm trying to use your library but I'm encountering this issue: no matter which style I choose, the active options don't show up the active styles. Here is a picture to show the effect:
![captura de pantalla 2015-06-05 a la s 21 12 15](https://cloud.githubusercontent.com/assets/1005398/8023373/3e91a53c-0d0a-11e5-97ed-d7bb6f461c4c.png)

Did you know why this is happening?
Thanks!

**Comment by Garito** [comment]
By the way: I'm using the lastest version of Bootstrap but I've tryed the same version from the examples but in the CDN without success

**Comment by Garito** [comment]
Update:
The on/off switch works ok with candy but do the same effect (not active feedback) in bootstrap (with well)

Is this perhaps a bootstrap 3 problem?

Thanks!

**Comment by ghinda** [comment]
I can't replicate the issue you're having. Here is a `switch-toggle` using the latest Bootstrap with `well` and `btn` elements:

http://jsbin.com/duwono/1/edit?html,css,output

**Comment by Garito** [comment]
I do: http://codepen.io/Garito/pen/qdjGpB?editors=110

**Comment by ghinda** [comment]
You didn't include the `a` element. Here you go:

http://codepen.io/anon/pen/VLzYPV

**Comment by Garito** [comment]
It work super nice!
Thank you very much

You know, I'm the technical cofounder of TimeFounder (https://app.timefounder.com) which is a fair and elegant equity split system where we give equity to the people who help in the projects registered there (ours included as you may expect) in form of T:F coins so seems to me obvious to pay you back for your help here in this way

If you like this deal I could transfer you 240 T:F coins (so 4 hours or work) to this project: https://app.timefounder.com/projects/t:f-0-3 that we use as issues for the 0.3 version of our app (you could see a better picture of this on the 0.2 version here: https://app.timefounder.com/projects/issues)
If so, send me your email (that's the only thing I need) by private at garito in the google mail system or ask for an invitation to T:F here: https://app.timefounder.com (I personaly send you the invitation)

To be honest, right now there is no value on this points because we are in an alpha stage but we are working to make this way to work available (I'm done with bosses, I prefer to be an investor but the only thing I have to do so is time, that's why we are working on T:F: you become a founder by investing your time)

If you are not interested: thanks a lot hope I could help you back soon
