### ISSUE TITLE
Is this library maintained?

### ISSUE THREAD

**Issue by Garito** [ghinda/css-toggle-switch#43]
Hi!
Would like to know if you are actively maintaining this library

It's worth to spend time on it?

Thanks!

**Comment by ghinda** [comment]
It's definitely maintained, but I'm not really planning to add new features to it, except maybe new themes or polishes to the existing ones.

Other than that, I try to get bugs fixed as soon as can.

**Comment by Garito** [comment]
A, ok!
I was asking this because the last update is 5 months ago and I was asking for a bug with no answer

**Comment by Garito** [comment]
You said you take care of this code but you don't answer the issues?

**Comment by ghinda** [comment]
I'm sure you realize this is an open source project that I work on for free, without any sort of compensation, in my free time.

I did see the issue you posted. You opened it just 4 days ago, so be patient, I'll get to it. 
Posting comments like these is not going to help.

**Comment by Garito** [comment]
Sure, but let me explain you that I don't expetct the correct answer right here right now
I was only asking for a feed back: "Let me try to reproduce this issue (or even better try yourself to reproduce it on jsbin or similar)"

I understand the open source thing but put yourself in my shoes (or in the someone else trying to use your library)

It is more important that any library maker to let his users to know he will take care than the solution itself

Hope you are not offended, if so, let me ask for sorry, this wasn't my intention for sure
Thanks for your help!
