### ISSUE TITLE
Remove label text margin on "Light switch" or move it on top

### ISSUE THREAD

**Issue by Kostanos** [ghinda/css-toggle-switch#45]
Currently it is set to 6.25em, is there any way to remove it completely?
Or move it on top like it is on ```Toggle switch```

In my case I need to put the label vertically (above input element), not horizontally like it hard-codded right now.

**Comment by ghinda** [comment]
Sure you can, here you go:
http://jsbin.com/yapota/edit?html,css,output

**Comment by Kostanos** [comment]
Thanks
