### ISSUE TITLE
"Material design" theme

### ISSUE THREAD

**Issue by itsravenous** [ghinda/css-toggle-switch#46]
Would be great to have a "material" theme:

![Material toggles](http://i.imgur.com/HAouibA.png)

Happy to submit a PR when I get time if you think it'd be something desirable. Not sure how tri/n-state buttons would work though.

**Comment by ghinda** [comment]
Great idea. I'll try to take a stab at it later this week.

**Comment by ghinda** [comment]
Available in `4.0.0`. https://ghinda.net/css-toggle-switch/

**Comment by itsravenous** [comment]
Very nice!
