### ISSUE TITLE
Bug when viewed in Firefox

### ISSUE THREAD

**Issue by Spudley** [ghinda/css-toggle-switch#49]
Hi.

I was just trying out your CSS toggle switches, but I found that they don't work very smoothly in Firefox.

The two-state (on/off) buttons are fine, but the "Week / Month / Year" and "Disabled / ADB / DevTools" toggles on the demo page have an issue.

The problem is that when I click on the control to trigger it to toggle, the text jumps a short distance to the left. In the case of "Disabled", it jumps far enough that part of the "D" becomes obscured by the container border. The toggle switches continue to work, but all three (or more) buttons are offset from their intended position, so it doesn't look right.

This issue does not occur in Chrome or IE11.

**Comment by ghinda** [comment]
Fixed and released as `4.0.1`. Thanks for reporting! :beer:
