### ISSUE TITLE
jsDelivr install option not working

### ISSUE THREAD

**Issue by Rarst** [ghinda/css-toggle-switch#52]
readme has jsDelivr install instructions, but neither project page or stylesheet links seem to be working.

Not sure if it _was_ working or just added for _future_ use since there seems to be open PR about it https://github.com/jsdelivr/jsdelivr/pull/8252

**Comment by ghinda** [comment]
It was supposed to be a placeholder until the PR got merged, but I think I accidentally pushed it to master.

The PR got merged and I fixed the url in the README.

Thanks for reporting! :beers:
