### ISSUE TITLE
Label with Div's height

### ISSUE THREAD

**Issue by danieljmg** [ghinda/css-toggle-switch#55]
Hi Mate,

I'm long time user of your library. I've just updated it, but I have the problem of the label not covering all div and also not centered at the div's height, every content gets alligned to the top. Ive been several hours, and I'm not ablet to solve it with post CSS. Can you give me a hint? Regards:

In this image, unless i click on the text, doesn't select. I want that to happend and also the text being vertically centered.
![centertext](https://cloud.githubusercontent.com/assets/7230125/14829879/0f3f2618-0bee-11e6-84da-80340867e823.png)

PD:With the previous version installed ( i recall 3.1.1) didn't happend.

**Comment by danieljmg** [comment]
Ok, first thing solved. Adding 
    display: flex; to switch-toggle covers all the div. Now i just need to center the text.

**Comment by ghinda** [comment]
Hi,

Here you go:
http://jsbin.com/vapivu/edit?html,css,output

Add the CSS snippet to your stylesheet, and it should work everywhere.

The downside of this approach is that you can't use Bootstrap/Foundation grid classes directly on the `.switch-toggle` element. You'll need an extra wrapper element around it with the sizing class (eg. `col-lg-4`, `large-4`).

**Comment by danieljmg** [comment]
Thanks man,

It does trully works with the version uploaded in the CDN. I've just tried with it.

It doesn't work with the latest version from this github though.

Anyway, I'll just probably use your CDN. Regards.

**Comment by ghinda** [comment]
That's weird. It should be the same.
Thanks for reporting, I'll take a look.
