### ISSUE TITLE
Please show focus indicators

### ISSUE THREAD

**Issue by mpnkhan** [ghinda/css-toggle-switch#58]
For example, focus indicator on wireless and airplane mode example, couldn't see focus indicator.

**Comment by ghinda** [comment]
It does have a focus outline. It's just that default shade of blue is very similar to the blue used on the hero background.

The color for the outline is from the os/browser:
https://github.com/ghinda/css-toggle-switch/blob/master/src/core/shared.scss#L31-L43

It's more visible further down on the grey background:
![screenshot_20170508_113649](https://cloud.githubusercontent.com/assets/325171/25796652/0970f9aa-33e3-11e7-8e56-b3f7e6eced86.png)
