### ISSUE TITLE
Set width 100% if just one option available

### ISSUE THREAD

**Issue by screeper** [ghinda/css-toggle-switch#63]
If you have a changing set of options and there is the case of just one possible option, the width of the label doesn't stretch. At least for the holo theme... I didn't check it width the other ones.
I think it can be solved quite easy by adding a width of 100% to `.switch-holo a` and `.switch-toggle input + label`.

**Comment by ghinda** [comment]
Can you make a small http://jsbin.com/ (or similar) demo, so I can see exactly what the issue is?
