### ISSUE TITLE
Multiple toggle switches on a page interact with each other

### ISSUE THREAD

**Issue by NathanOTWeb** [ghinda/css-toggle-switch#64]
I'm trying to use this multiple times on a webpage, but they seem to interacting with each other.  When I set a switch to be "on," if another switch is already "on," that one moves to "off." Not sure if I'm doing something wrong.  All the ids are different and id attributes match for attributes.  This is a case where I can't switch the "on" to be the "off".

**Comment by ghinda** [comment]
Can you please check that each group of radios has a unique `name` attribute? For example, the first group should all have `name="group-1"`, the next group should have `name="group-2"`.

**Comment by NathanOTWeb** [comment]
Thanks, that did the trick.
